#!/bin/sh

warnings=$(grep -Po 'case (class|object) [a-zA-Z0-9_]+' src/main/scala/Warning.scala | cut -d' ' -f3 | tr '\n' ' ')
i=0
for w in $warnings; do
    test=$(grep -Pn "def $w[(][)]" src/test/scala/LinterPluginTest.scala)
    if [ "$test" != "" ]; then
        echo -n "[$w](src/test/scala/LinterPluginTest.scala#L$(echo $test | cut -d':' -f1)), "
    else
        echo -n "$w, "
    fi
    i=$((i+1))
done

echo
echo "## List of implemented checks ($i)"
